inherit_from:
  - ruby/rubocop_strict.yml
  - ruby/rubocop_rspec_strict.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - "sgcop.gemspec"

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/Output:
  Enabled: true
