require 'rubocop'
require 'sgcop/version'
require 'sgcop/inject'

Sgcop::Inject.defaults!

require 'rubocop/cop/sgcop/simple_format'
require 'rubocop/cop/sgcop/request_remote_ip'
require 'rubocop/cop/sgcop/simple_form_association'
require 'rubocop/cop/sgcop/unscoped'
require 'rubocop/cop/sgcop/ujs_options'
require 'rubocop/cop/sgcop/active_job_queue_adapter'
require 'rubocop/cop/sgcop/on_load_arguments'
require 'rubocop/cop/sgcop/transaction_requires_new'
require 'rubocop/cop/sgcop/load_defaults_version_match'
require 'rubocop/cop/sgcop/retry_on_infinite_attempts'
require 'rubocop/cop/sgcop/capybara/sleep'
require 'rubocop/cop/sgcop/capybara/matchers'
require 'rubocop/cop/sgcop/capybara/fragile_selector'
require 'rubocop/cop/sgcop/resource_action_order'
require 'rubocop/cop/sgcop/resources_without_only'
require 'rubocop/cop/sgcop/strict_loading_required'
require 'rubocop/cop/sgcop/enumerize_default_option'
require 'rubocop/cop/sgcop/enumerize_predicates_option'
require 'rubocop/cop/sgcop/hash_fetch_default'
require 'rubocop/cop/sgcop/rspec/action_mailer_test_helper'
require 'rubocop/cop/sgcop/rspec/redundant_perform_enqueued_jobs'
require 'rubocop/cop/sgcop/rspec/redundant_let_reference'
require 'rubocop/cop/sgcop/capybara/spec_stability_check'
require 'rubocop/cop/sgcop/no_accepts_nested_attributes_for'
require 'rubocop/cop/sgcop/nested_resources_without_module'
require 'rubocop/cop/sgcop/error_message_format'
require 'rubocop/cop/sgcop/restricted_view_helpers'
require 'rubocop/cop/sgcop/strftime_restriction'
require 'rubocop/cop/sgcop/prefer_absolute_path_partial'
