Sgcop/Unscoped:
  Description: "絞り込みが全解除されるので見えてはいけないものが見えてしまう可能性があるよ"
  Enabled: true
  Reference:
    - https://techracho.bpsinc.jp/hachi8833/2021_11_04/47302

Sgcop/SimpleFormat:
  Description: "simple_formatでエスケープされていないときに警告"
  Enabled: true

Sgcop/SimpleFormAssociation:
  Description: "simple_formのassociationメソッドではcollectionを明示しよう"
  Enabled: true

Sgcop/RequestRemoteIp:
  Description: "クライアントのIPを取得するならrequest.remote_ipの必要があるよ"
  Enabled: true
  Reference:
    - https://api.rubyonrails.org/classes/ActionDispatch/Request.html#method-i-remote_ip-3D

Sgcop/Whenever:
  Description: "24時間表記で書かないと意図しない時間でcrontab設定される可能性あるよ"
  Enabled: true
  Include:
    - "config/schedule.rb"
  Reference:
    - https://github.com/javan/whenever#parsing-dates-and-times
Sgcop/UjsOptions:
  Description: "Rails UJS Attributesは非推奨となっているよ"
  Enabled: true
  Reference:
    - https://edgeapi.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to-label-Deprecated-3A+Rails+UJS+Attributes

Sgcop/Capybara/Sleep:
  Description: "sleepに頼らない安定したspecを書こう"
  Enabled: true
  Include:
    - "spec/features/**/*_spec.rb"
    - "spec/system/**/*_spec.rb"
  Reference:
    - https://qiita.com/shunichi/items/1cb7f7cfca74438513d3

Sgcop/Capybara/Matchers:
  Description: "マッチャーの書き方を統一"
  Enabled: true
  Include:
    - "spec/features/**/*_spec.rb"
    - "spec/system/**/*_spec.rb"
  PreferredMethods:
    have_text: "have_content"
