Sgcop/Unscoped:
  Description: "絞り込みが全解除されるので見えてはいけないものが見えてしまう可能性があるよ"
  Enabled: true
  Reference:
    - https://techracho.bpsinc.jp/hachi8833/2021_11_04/47302

Sgcop/SimpleFormat:
  Description: "simple_formatでエスケープされていないときに警告"
  Enabled: true

Sgcop/SimpleFormAssociation:
  Description: "simple_formのassociationメソッドではcollectionを明示しよう"
  Enabled: true

Sgcop/RequestRemoteIp:
  Description: "クライアントのIPを取得するならrequest.remote_ipの必要があるよ"
  Enabled: true
  Reference:
    - https://api.rubyonrails.org/classes/ActionDispatch/Request.html#method-i-remote_ip-3D

Sgcop/UjsOptions:
  Description: "Rails UJS Attributesは非推奨となっているよ"
  Enabled: true
  Reference:
    - https://edgeapi.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to-label-Deprecated-3A+Rails+UJS+Attributes

Sgcop/ActiveJobQueueAdapter:
  Description: "config/initializers以下で設定しても効かないよ"
  Enabled: true
  Include:
    - "config/initializers/*.rb"
  Reference:
    - https://qiita.com/sukechannnn/items/6cf8933c78656f543d54

Sgcop/OnLoadArguments:
  Description: ActiveSupport.on_loadの引数が許可されていないnameだよ
  Enabled: true
  AllowedNames:
    - action_cable
    - action_cable_channel
    - action_cable_connection
    - action_cable_connection_test_case
    - action_controller_api
    - action_controller
    - action_controller_base
    - action_controller_test_case
    - action_dispatch_integration_test
    - action_dispatch_response
    - action_dispatch_request
    - action_dispatch_system_test_case
    - action_mailbox
    - action_mailbox_inbound_email
    - action_mailbox_record
    - action_mailbox_test_case
    - action_mailer
    - action_mailer_test_case
    - action_text_content
    - action_text_record
    - action_text_rich_text
    - action_text_encrypted_rich_text
    - action_view
    - action_view_test_case
    - active_job
    - active_job_test_case
    - active_model
    - active_record
    - active_record_fixtures
    - active_record_postgresqladapter
    - active_record_mysql2adapter
    - active_record_trilogyadapter
    - active_record_sqlite3adapter
    - active_storage_attachment
    - active_storage_variant_record
    - active_storage_blob
    - active_storage_record
    - active_support_test_case
    - i18n
  Reference:
    - https://github.com/rails/rails/blob/e9b61852343c83365aa73db6abcfae1e5b31272f/guides/source/configuring.md?plain=1#L3591

Sgcop/TransactionRequiresNew:
  Description: "`requires_new: true`オプションを付けないとネストしたトランザクションでロールバックされない可能性があるよ"
  Enabled: true
  Reference:
    - https://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html#module-ActiveRecord::Transactions::ClassMethods-label-Nested+transactions

Sgcop/LoadDefaultsVersionMatch:
  Description: "Railsのバージョンとload_defaultsのバージョンが揃っていないよ"
  Enabled: true
  Include:
    - "config/application.rb"

Sgcop/RetryOnInfiniteAttempts:
  Description: "永遠にリトライする可能性があって危険だよ"
  Enabled: true
  Include:
    - "app/jobs/*.rb"
    - "config/initializers/*.rb"

Sgcop/Capybara/Sleep:
  Description: "sleepに頼らない安定したspecを書こう"
  Enabled: true
  Include:
    - "spec/features/**/*_spec.rb"
    - "spec/system/**/*_spec.rb"
  Reference:
    - https://qiita.com/shunichi/items/1cb7f7cfca74438513d3

Sgcop/Capybara/Matchers:
  Description: "マッチャーの書き方を統一"
  Enabled: true
  Include:
    - "spec/features/**/*_spec.rb"
    - "spec/system/**/*_spec.rb"
  PreferredMethods:
    have_text: "have_content"

Sgcop/Capybara/FragileSelector:
  Description: "スタイル変更やマークアップ変更で壊れやすいセレクタの使用を避けよう"
  Enabled: false
  Include:
    - "spec/system/**/*_spec.rb"

Sgcop/ResourceActionOrder:
  Description: "routes.rbでのresource/resources内のaction順序をRails/ActionOrderと同じ順序に統一"
  Enabled: true
  Include:
    - "config/routes.rb"
    - "config/routes/*.rb"

Sgcop/ResourcesWithoutOnly:
  Description: "resourcesルーティングには`only:`オプションを使用しよう"
  Enabled: true
  Include:
    - "config/routes.rb"
    - "config/routes/*.rb"

Sgcop/StrictLoadingRequired:
  Description: "includesやpreloadを使用して変数代入する場合はstrict_loadingを追加することで仕組みでN+1を防ごう"
  Enabled: false
  Reference:
    - https://guides.rubyonrails.org/active_record_querying.html#strict-loading
  Include:
    - "app/controllers/**/*.rb"
    - "app/components/**/*.rb"

Sgcop/EnumerizeDefaultOption:
  Description: "enumerizeのdefaultオプションは予測しない挙動を引き起こすため使用を避けてデータベースレベルでデフォルト値を設定しよう"
  Enabled: false
  Include:
    - "app/models/*.rb"

Sgcop/EnumerizePredicatesOption:
  Description: "enumerizeのpredicatesオプションの使用を制限する（メソッド名がコンフリクトしやすく、定義を追いにくくなるため）"
  Enabled: false
  AllowWithPrefix: false # trueにすると predicates: { prefix: true } の場合は許可
  Include:
    - "app/models/**/*.rb"

Sgcop/ErrorMessageFormat:
  Description: "エラーメッセージはシンボルで指定しよう。エラーの種別で検証することで壊れにくいテストが書けます。"
  Enabled: false
  Include:
    - "app/models/**/*.rb"
    - "app/forms/**/*.rb"
    - "app/validators/**/*.rb"
  Reference:
    - https://guides.rubyonrails.org/i18n.html#translations-for-active-record-models

Sgcop/HashFetchDefault:
  Description: "Hash#fetchを使用してデフォルト値を扱うことでfalseyな値を保持しよう"
  Enabled: true
  Reference:
    - https://rubystyle.guide/#hash-fetch-defaults

Sgcop/Rspec/ActionMailerTestHelper:
  Description: "ActionMailer::Base.deliveriesの代わりにActionMailer::TestHelperのメソッドを使用しよう"
  Enabled: false
  Include:
    - "spec/**/*_spec.rb"
  Reference:
    - https://api.rubyonrails.org/classes/ActionMailer/TestHelper.html

Sgcop/Rspec/RedundantPerformEnqueuedJobs:
  Description: "ActionMailer::TestHelperのメソッドは内部でperform_enqueued_jobsを使用しているため、外側のperform_enqueued_jobsは冗長だよ"
  Enabled: true
  Include:
    - "spec/**/*_spec.rb"
  Reference:
    - https://api.rubyonrails.org/classes/ActionMailer/TestHelper.html
    - https://github.com/rails/rails/blob/main/actionmailer/lib/action_mailer/test_helper.rb

Sgcop/Rspec/RedundantLetReference:
  Description: "letを参照するだけの無意味な処理を検出し、let!の使用や直接セットアップを推奨"
  Enabled: true
  Include:
    - "spec/**/*_spec.rb"

Sgcop/Rspec/ConditionalExample:
  Description: "条件付きexpectを避け、常に無条件でアサーションを行うことを推奨"
  Enabled: true
  Include:
    - "spec/**/*_spec.rb"

Sgcop/Rspec/NoMethodCallInExpectation:
  Description: "期待値でメソッド呼び出しではなくリテラル値を使用しよう"
  Enabled: false
  Include:
    - "spec/**/*_spec.rb"
  TargetMatchers:
    - have_content
    - have_text
    - have_css
    - have_selector
    - have_title
    - eq
    - eql
    - equal
    - include
    - match
  AllowedPatterns:
    - "_path$"
    - "_url$"
    - "^I18n\\.t$"
    - "^I18n\\.l$"

Sgcop/NoAcceptsNestedAttributesFor:
  Description: "accepts_nested_attributes_forの使用を避けよう。DHHはこの機能をRailsから削除したがっている。Form Objectsの使用を検討しよう"
  Enabled: false
  Include:
    - "app/models/**/*.rb"
  Reference:
    - https://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html
    - https://github.com/rails/rails/issues/41419

Sgcop/NestedResourcesWithoutModule:
  Description: "ネストしたresourcesルーティングには`module:`オプションを使用しよう"
  Enabled: false
  Include:
    - "config/routes.rb"
    - "config/routes/*.rb"

Sgcop/RestrictedViewHelpers:
  Description: "特定のビューヘルパーメソッドの使用を制限"
  Enabled: true
  Include:
    - "app/views/**/*.erb"
    - "app/helpers/**/*.rb"
    - "app/components/**/*.rb"
  RestrictedMethods: []

Sgcop/StrftimeRestriction:
  Description: "strftimeではなくI18n.lを使用してローカライズしてください"
  Enabled: true
  AllowedPatterns:
    - "%a"  # 曜日の省略名 (Sun, Mon, etc.)
    - "%A"  # 曜日の完全名 (Sunday, Monday, etc.)
    - "%w"  # 曜日の数字 (0=Sunday, 1=Monday, etc.)
  Reference:
    - https://guides.rubyonrails.org/i18n.html#adding-date-time-formats

Sgcop/I18nLocalizeFormatString:
  Description: "I18n.lのformatオプションには文字列ではなくシンボルを使用してください。ロケールファイルに定義してシンボルで参照することで、ロケールごとの切り替えが可能になります"
  Enabled: true
  Reference:
    - https://guides.rubyonrails.org/i18n.html#adding-date-time-formats

Sgcop/PreferAbsolutePathPartial:
  Description: "パーシャルファイルのrenderは絶対パスで指定しよう"
  Enabled: true
  Include:
    - "app/views/**/*"
    - "app/components/**/*"

Sgcop/Capybara/SpecStabilityCheck:
  Description: "非同期処理を伴うテストでは適切な待機処理を追加してテストを安定させよう"
  Enabled: true
  Include:
    - "spec/system/**/*_spec.rb"
  WatchedMethods:
    - assert_enqueued_emails
    - assert_emails
    - assert_no_emails
    - assert_enqueued_jobs
    - capture_emails
    - expect
  WaitMatchers:
    - have_content
    - have_text
    - have_css
    - have_selector
