Sgcop/SimpleFormat:
  Description: "simple_formatでエスケープされていないときに警告"
  Enabled: true

Sgcop/Sleep:
  Description: "テストではsleep禁止"
  Enabled: true
  Include:
    - "**/*_spec.rb"
  Reference:
    - https://qiita.com/syossan27/items/78c479a46dcf963f55ef
    - https://katsulog.tech/i-do-not-recommend-using-sleep-when-waiting-for-elements/
