Sgcop/SimpleFormat:
  Description: "simple_formatでエスケープされていないときに警告"
  Enabled: true

Sgcop/Sleep:
  Description: "sleepに頼らない安定したspecを書こう"
  Enabled: true
  Include:
    - "**/*_spec.rb"
  Reference:
    - https://qiita.com/shunichi/items/1cb7f7cfca74438513d3
