#!/usr/bin/env ruby

if ARGV.empty?
  exec 'rubocop'
elsif ARGV[0] != 'review'
  puts 'Usage: sgcop review [script name]'
  exit
end
script_name = ARGV[1]
shell_script_path = File.join(__dir__, "review-#{script_name}.sh")

system(shell_script_path) || exit(Process.last_status.exitstatus)
